FitnessWebApp/Controllers/ChatController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GymWebApp.Controllers
{
    [Authorize]
    public class ChatController : Controller
    {
        
        public IActionResult Index()
        {
            return View();
        }
    }
}

FitnessWebApp/Controllers/ReservationsController.cs
using GymWebApp.Data.Services;
using GymWebApp.Data.ViewModels;
using GymWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;

namespace GymWebApp.Controllers
{
    [Authorize]
    public class ReservationsController : Controller
    {
        private readonly IReservationsServices _service;

        public ReservationsController(IReservationsServices service)
        {
            _service = service;
        }

        
        public async Task<IActionResult> Index()
        {
            var reservations = Enumerable.Empty<Reservation>();

            if (User.IsInRole("Admin"))
            {
                reservations = await _service.GetAllAsync(m => m.Training, m => m.User);
            }
            else
            {
                var username = User.Identity.Name;
                reservations = await _service.GetAllAsync(m => m.User.UserName == username, m => m.Training, m => m.User);
            }

            return View(reservations);
        }

        
        public async Task<IActionResult> Details(int id)
        {
            var reservationDetails = await _service.GetReservationByIdAsync(id);
            return View(reservationDetails);
        }

        
        public async Task<IActionResult> Create()
        {
            var reservationDropDownsValue = await _service.GetReservationDropDownsData();
            ViewBag.Trainings = new SelectList(reservationDropDownsValue.Trainings, "Id", "Name");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ReservationVM reservation)
        {
            if (!ModelState.IsValid)
            {
                var reservationDropDownsValue = await _service.GetReservationDropDownsData();
                ViewBag.Trainings = new SelectList(reservationDropDownsValue.Trainings, "Id", "Name");
                return View(reservation);
            }

            var username = User.Identity.Name;
            await _service.AddReservationAsync(reservation, username);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {
            var reservationDetails = await _service.GetReservationByIdAsync(id);

            if (reservationDetails == null) return View("NotFound");

            var outcome = new ReservationVM();
            outcome.Id = reservationDetails.Id;
            outcome.ParticipationHour = reservationDetails.ParticipationHour;
            outcome.ParticipationDate = reservationDetails.ParticipationDate;
            outcome.TrainingId = reservationDetails.TrainingId;

            var reservationDropDownsValue = await _service.GetReservationDropDownsData();
            ViewBag.Trainings = new SelectList(reservationDropDownsValue.Trainings, "Id", "Name");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, ReservationVM reservation)
        {
            if (id != reservation.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var reservationDropDownsValue = await _service.GetReservationDropDownsData();
                ViewBag.Trainings = new SelectList(reservationDropDownsValue.Trainings, "Id", "Name");
                return View(reservation);
            }
            await _service.UpdateReservationAsync(reservation);
            return RedirectToAction(nameof(Index));
        }
    }
}

FitnessWebApp/Controllers/TrainersController.cs
using GymWebApp.Data.Services;
using GymWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace GymWebApp.Controllers
{
    [Authorize]
    public class TrainersController : Controller
    {
       
        private readonly ITrainersServices _service;

        public TrainersController(ITrainersServices service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allTrainers = await _service.GetAllAsync();
            return View(allTrainers);
        }

        //get:trainer/create
        public IActionResult Create()
        {
            return View();
        }

        //pentru a trimite datele in bd
        [HttpPost]
        public async Task<IActionResult> Create([Bind("FirstName, LastName, Biography, ProfilePicture")] Trainer trainer)
        {
            if (!ModelState.IsValid)
            {
                return View(trainer);
            }

            await _service.AddAsync(trainer);
            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]
        //get:trainer/details 
        public async Task<IActionResult> Details(int id)
        {
            var trainerDetails = await _service.GetByIdAsync(id);

            if (trainerDetails == null) return View("NotFound");
            return View(trainerDetails);
        }

      

        public async Task<IActionResult> Edit(int id)
        {
            var trainerDetails = await _service.GetByIdAsync(id);
            if (trainerDetails == null) return View("NotFound");
            return View(trainerDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,ProfilePicture,Biography")] Trainer trainer)
        {
            if (!ModelState.IsValid)
            {  
                return View(trainer);
            }

            await _service.UpdateAsync(id, trainer);
            return RedirectToAction(nameof(Index));
        }


        //get:stergere antrenor
        public async Task<IActionResult> Delete(int id)
        {
            var trainerDetails = await _service.GetByIdAsync(id);
            if (trainerDetails == null) return View("NotFound");
            return View(trainerDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteValidation(int id)
        {
            var trainerDetails = await _service.GetByIdAsync(id);
            if (trainerDetails == null) return View("NotFound");
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

FitnessWebApp/Controllers/TrainingsController.cs
using GymWebApp.Data.Services;
using GymWebApp.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GymWebApp.Controllers
{
    [Authorize]
    public class TrainingsController : Controller
    {
        private readonly ITrainingsServices _service;

        public TrainingsController(ITrainingsServices service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allTrainings = await _service.GetAllAsync(m => m.Trainer);
            return View(allTrainings);
        }

        [AllowAnonymous]
        //get/training/details
        public async Task<IActionResult> Details(int id)
        {
            var trainingDetails = await _service.GetTrainingByIdAsync(id);
            return View(trainingDetails);

        }

        public async Task<IActionResult> Create()
        {
            var trainingDropDownValue = await _service.GetTrainingDropDownsData();
            ViewBag.Trainers = new SelectList(trainingDropDownValue.Trainers, "Id", "FirstName");
            ViewBag.Subscriptions = new SelectList(trainingDropDownValue.Subscriptions, "Id", "Name");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(TrainingVM training)
        {
            if (!ModelState.IsValid)
            {
                var trainingDropDownValue = await _service.GetTrainingDropDownsData();
                ViewBag.Trainers = new SelectList(trainingDropDownValue.Trainers, "Id", "FirstName");
                ViewBag.Subscriptions = new SelectList(trainingDropDownValue.Subscriptions, "Id", "Name");
                return View(training);
            }
            await _service.AddTrainingAsync(training);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {
            var trainingDetails = await _service.GetTrainingByIdAsync(id);
            if (trainingDetails == null) return View("NotFound");

            var outcome = new TrainingVM();
            outcome.Id = trainingDetails.Id;
            outcome.Name = trainingDetails.Name;
            outcome.Description = trainingDetails.Description;
            outcome.Picture = trainingDetails.Picture;
            outcome.StartHour = trainingDetails.StartHour;
            outcome.FinishHour = trainingDetails.FinishHour;
            outcome.Category = trainingDetails.Category;
            outcome.TrainerId = trainingDetails.TrainerId;
            outcome.SubscriptionId = trainingDetails.SubscriptionId;


            var trainingDropDownValue = await _service.GetTrainingDropDownsData();
            ViewBag.Trainers = new SelectList(trainingDropDownValue.Trainers, "Id", "FirstName");
            ViewBag.Subscriptions = new SelectList(trainingDropDownValue.Subscriptions, "Id", "Name");

            return View(outcome);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, TrainingVM training)
        {
            if (id != training.Id) return View("NotFound");


            if (!ModelState.IsValid)
            {
                var trainingDropDownValue = await _service.GetTrainingDropDownsData();
                ViewBag.Trainers = new SelectList(trainingDropDownValue.Trainers, "Id", "FirstName");
                ViewBag.Subscriptions = new SelectList(trainingDropDownValue.Subscriptions, "Id", "Name");
                return View(training);
            }
            await _service.UpdateTrainingAsync(training);
            return RedirectToAction(nameof(Index));
        }
    }
}

FitnessWebApp/Views/Shared/Index.cshtml
@{
    ViewData["Title"] = "LiveChat";
}
<div class="container">
    <div class="row">&nbsp;</div>
    <div class="row">
        <div class="col-2">Utilizator: </div>
        <div class="col-4"><input asp-for="@User.Identity.Name" id="userInput" readonly /></div>
    </div>
    <br/>
    <div class="row">
        <div class="col-2">Mesaj: </div>
        <div class="col-4"><textarea type="text" id="messageInput"></textarea></div>
    </div>
    <div class="row">&nbsp;</div>
    <div class="row">
        <div class="col-6">
            <input type="button" class="btn btn-info" id="sendButton" value="Trimite Mesaj" />
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <hr />
    </div>
</div>
<div class="row">
    <div class="col-6">
        <ul id="messagesList"></ul>
    </div>
</div>

<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="~/js/chat.js"></script>

FitnessWebApp/Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-10 offset-3">
        <h2>Cererea ta nu există!</h2>
        <a class="btn-danger" asp-controller="" asp-action="">Înapoi</a>
    </div>


</div>

FitnessWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FitnessWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RevolutionGym</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="navbar-nav">
                            <a class="nav-link text-dark" asp-controller="Subscriptions" asp-action="Index"><i class="bi bi-justify"></i>Abonamente</a>
                        </li>

                        <li class="navbar-nav">
                            <a class="nav-link text-dark" asp-controller="Trainings" asp-action="Index"><i class="bi bi-dribbble"></i>Clase</a>
                        </li>

                        <li class="navbar-nav">
                            <a class="nav-link text-dark" asp-controller="Trainers" asp-action="Index"><i class="bi bi-people"></i>Antrenori</a>
                        </li>

                       @* @if (User.Identity.IsAuthenticated)*@
                        
                            <li class="navbar-nav">
                                <a class="nav-link text-dark" asp-controller="Reservations" asp-action="Index"><i class="bi bi-journal-check"></i>Rezervări</a>
                            </li>

                            <li class="navbar-nav">
                                <a class="nav-link text-dark" asp-controller="Chat" asp-action="Index"><i class="bi bi-chat-dots"></i>Chat</a>
                            </li>
                        



                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FitnessWebApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>