FitnessWebApp/Models/Training.cs
using GymWebApp.Data.BaseRepository;
using GymWebApp.Data.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GymWebApp.Models
{
    public class Training : IEntityBase
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Nume Antrenament")]
        [Required(ErrorMessage = "Caseta 'Nume' trebuie completată!")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Caseta 'Prenumele' trebuie să conțină între 3 și 50 caractere!")]
        public string Name { get; set; }

        [Display(Name = "Descriere")]
        [Required(ErrorMessage = "Caseta 'Descriere' trebuie completată!")]
        public string Description { get; set; }

        [Display(Name = "Imagine")]
        public string Picture { get; set; }

        [Display(Name = "Selectează Ora începerii")]
        [Required(ErrorMessage = "Caseta 'Ora începerii' trebuie completată!")]
        public DateTime StartHour { get; set; }

        [Display(Name = "Selectează Ora finalizării")]
        [Required(ErrorMessage = "Caseta 'Ora finalizării' trebuie completată!")]
        public DateTime FinishHour { get; set; }

        [Display(Name = "Selectează Categoria antrenamentului")]
        [Required(ErrorMessage = "Caseta 'Categoria antrenamentului' trebuie completată!")]
        public TrainingCategory Category { get; set; }

        //relatia cu rezervarile
        public List<Reservation> Reservations { get; set; }


        //relatia cu antrenorii
        public int TrainerId { get; set; }
        public Trainer Trainer { get; set; }

        //relatia cu abonamentele
        public int SubscriptionId { get; set; }
        public Subscription Subscription { get; set; }
    }
}

FitnessWebApp/Controllers/SubscriptionsController.cs
using GymWebApp.Data.Services;
using GymWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GymWebApp.Controllers
{
    [Authorize]
    public class SubscriptionsController : Controller
    {
        private readonly ISubscriptionsServices _service;

        public SubscriptionsController(ISubscriptionsServices service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allSubscriptions = await _service.GetAllAsync();
            return View(allSubscriptions);
        }


        [AllowAnonymous]
        //get/details
        public async Task<IActionResult> Details(int id)
        {
            var subscriptiondetails = await _service.GetByIdAsync(id);
            if (subscriptiondetails == null) return View("NotFound");
            return View(subscriptiondetails);
        }

        //get/create
        public IActionResult Create()
        {
            return View();
        }

        //pt bd
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name,Validity,Picture,Price,Description")] Subscription subscription)
        {
            if (!ModelState.IsValid)
            {
                return View(subscription);
            }

            await _service.AddAsync(subscription);
            return RedirectToAction(nameof(Index));
        }

        //get:editare 
        public async Task<IActionResult> Edit(int id)
        {
            var subscriptionDetails = await _service.GetByIdAsync(id);
            if (subscriptionDetails == null) return View("NotFound");
            return View(subscriptionDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Validity,Picture,Price,Description")] Subscription subscription)
        {
            if (!ModelState.IsValid)
            {
                return View(subscription);
            }

            if (id == subscription.Id)
            {
                await _service.UpdateAsync(id, subscription);
                return RedirectToAction(nameof(Index));
            }
            return View(subscription);
        }

        //get:stergere 
        public async Task<IActionResult> Delete(int id)
        {
            var subscriptionDetails = await _service.GetByIdAsync(id);
            if (subscriptionDetails == null) return View("NotFound");
            return View(subscriptionDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteValidation(int id)
        {
            var subscriptionDetails = await _service.GetByIdAsync(id);
            if (subscriptionDetails == null) return View("NotFound");
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

FitnessWebApp/Controllers/TrainersController.cs
using GymWebApp.Data.Services;
using GymWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace GymWebApp.Controllers
{
    [Authorize]
    public class TrainersController : Controller
    {
       
        private readonly ITrainersServices _service;

        public TrainersController(ITrainersServices service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allTrainers = await _service.GetAllAsync();
            return View(allTrainers);
        }

        //get:trainer/create
        public IActionResult Create()
        {
            return View();
        }

        //pentru a trimite datele in bd
        [HttpPost]
        public async Task<IActionResult> Create([Bind("FirstName, LastName, Biography, ProfilePicture")] Trainer trainer)
        {
            if (!ModelState.IsValid)
            {
                return View(trainer);
            }

            await _service.AddAsync(trainer);
            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]
        //get:trainer/details 
        public async Task<IActionResult> Details(int id)
        {
            var trainerDetails = await _service.GetByIdAsync(id);

            if (trainerDetails == null) return View("NotFound");
            return View(trainerDetails);
        }

      

        public async Task<IActionResult> Edit(int id)
        {
            var trainerDetails = await _service.GetByIdAsync(id);
            if (trainerDetails == null) return View("NotFound");
            return View(trainerDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,ProfilePicture,Biography")] Trainer trainer)
        {
            if (!ModelState.IsValid)
            {  
                return View(trainer);
            }

            await _service.UpdateAsync(id, trainer);
            return RedirectToAction(nameof(Index));
        }


        //get:stergere antrenor
        public async Task<IActionResult> Delete(int id)
        {
            var trainerDetails = await _service.GetByIdAsync(id);
            if (trainerDetails == null) return View("NotFound");
            return View(trainerDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteValidation(int id)
        {
            var trainerDetails = await _service.GetByIdAsync(id);
            if (trainerDetails == null) return View("NotFound");
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

FitnessWebApp/Controllers/TrainingsController.cs
using GymWebApp.Data.Services;
using GymWebApp.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GymWebApp.Controllers
{
    [Authorize]
    public class TrainingsController : Controller
    {
        private readonly ITrainingsServices _service;

        public TrainingsController(ITrainingsServices service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allTrainings = await _service.GetAllAsync(m => m.Trainer);
            return View(allTrainings);
        }

        [AllowAnonymous]
        //get/training/details
        public async Task<IActionResult> Details(int id)
        {
            var trainingDetails = await _service.GetTrainingByIdAsync(id);
            return View(trainingDetails);

        }

        public async Task<IActionResult> Create()
        {
            var trainingDropDownValue = await _service.GetTrainingDropDownsData();
            ViewBag.Trainers = new SelectList(trainingDropDownValue.Trainers, "Id", "FirstName");
            ViewBag.Subscriptions = new SelectList(trainingDropDownValue.Subscriptions, "Id", "Name");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(TrainingVM training)
        {
            if (!ModelState.IsValid)
            {
                var trainingDropDownValue = await _service.GetTrainingDropDownsData();
                ViewBag.Trainers = new SelectList(trainingDropDownValue.Trainers, "Id", "FirstName");
                ViewBag.Subscriptions = new SelectList(trainingDropDownValue.Subscriptions, "Id", "Name");
                return View(training);
            }
            await _service.AddTrainingAsync(training);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {
            var trainingDetails = await _service.GetTrainingByIdAsync(id);
            if (trainingDetails == null) return View("NotFound");

            var outcome = new TrainingVM();
            outcome.Id = trainingDetails.Id;
            outcome.Name = trainingDetails.Name;
            outcome.Description = trainingDetails.Description;
            outcome.Picture = trainingDetails.Picture;
            outcome.StartHour = trainingDetails.StartHour;
            outcome.FinishHour = trainingDetails.FinishHour;
            outcome.Category = trainingDetails.Category;
            outcome.TrainerId = trainingDetails.TrainerId;
            outcome.SubscriptionId = trainingDetails.SubscriptionId;


            var trainingDropDownValue = await _service.GetTrainingDropDownsData();
            ViewBag.Trainers = new SelectList(trainingDropDownValue.Trainers, "Id", "FirstName");
            ViewBag.Subscriptions = new SelectList(trainingDropDownValue.Subscriptions, "Id", "Name");

            return View(outcome);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, TrainingVM training)
        {
            if (id != training.Id) return View("NotFound");


            if (!ModelState.IsValid)
            {
                var trainingDropDownValue = await _service.GetTrainingDropDownsData();
                ViewBag.Trainers = new SelectList(trainingDropDownValue.Trainers, "Id", "FirstName");
                ViewBag.Subscriptions = new SelectList(trainingDropDownValue.Subscriptions, "Id", "Name");
                return View(training);
            }
            await _service.UpdateTrainingAsync(training);
            return RedirectToAction(nameof(Index));
        }
    }
}

FitnessWebApp/Views/Trainings/Create.cshtml
@using GymWebApp.Data.ViewModels
@model TrainingVM
@using GymWebApp.Data.Enums
@{
    ViewData["Title"] = "Create new training";
}

<h2 class="text-center">Adaugă un antrenament nou</h2>
<br />
<div class="row">
    <div class="col-md-8 offset-2">
        <form method="post" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Picture" class="control-label"></label>
                        <input asp-for="Picture" class="form-control" />
                        <span asp-validation-for="Picture" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="StartHour" class="control-label"></label>
                        <input asp-for="StartHour" type="time" class="form-control" />
                        <span asp-validation-for="StartHour" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FinishHour" class="control-label"></label>
                        <input asp-for="FinishHour" type="time" class="form-control" />
                        <span asp-validation-for="FinishHour" class="text-danger"></span>
                    </div>



                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Category" class="control-label"></label>
                        <select asp-for="Category" class="form-control" asp-items="Html.GetEnumSelectList<TrainingCategory>()"></select>
                        <span asp-validation-for="Category" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="TrainerId" class="control-label"></label>
                        <select asp-for="TrainerId" class="form-control" asp-items="ViewBag.Trainers"></select>
                        <span asp-validation-for="TrainerId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SubscriptionId" class="control-label"></label>
                        <select asp-for="SubscriptionId" class="form-control" asp-items="ViewBag.Subscriptions"></select>
                        <span asp-validation-for="SubscriptionId" class="text-danger"></span>
                    </div>

                </div>

                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <textarea asp-for="Description" class="form-control"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
            </div>


            <div class="form-group">
                <input type="submit" value="Creează" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-primary float-right"><i class="bi bi-arrow-left-circle"></i>Înapoi la listă</a>
            </div>




        </form>
    </div>
</div>

FitnessWebApp/Views/Trainings/Details.cshtml
@using GymWebApp.Models
@model Training

@{
    ViewData["Title"] = "Details about a training";
}

<h1 class="text-center">Detalii despre antrenamentul </h1>
<br />
@*<div class="col-md-6 offset-2">*@
        <img src="@Model.Picture" class="align-baseline" alt="@Model.Name" style="max-width: 400px">
        <div class="card-block">
            <h4 class="card-title">@Model.Name</h4>
            <br />
            <p class="card-text">@Model.Description</p>
            <p class="card-text"><b>Ora începerii:</b>@Model.StartHour.ToString("HH:mm")</p>
            <p class="card-text"><b>Ora finalizării:</b>@Model.FinishHour.ToString("HH:mm")</p>
            <p class="card-text"><b>Categoria clasei:</b>@Model.Category.ToString()</p>
            <p class="card-text">
                <b>Antrenorul:</b>
                <a asp-controller="Trainers" asp-action="Details" asp-route-id="@Model.TrainerId">@Model.Trainer.FirstName</a>
            </p>
            <p class="card-text">
                <b>Abonament:</b>
                <a asp-controller="Subscriptions" asp-action="Details" asp-route-id="@Model.SubscriptionId">@Model.Subscription.Name</a>
            </p>


        </div>
   @* </div>*@

<div class="float-right">
    <a asp-action="Index" class="btn btn-primary"><i class="bi bi-arrow-left-circle"></i>Înapoi la listă</a>
</div>

FitnessWebApp/Views/Trainings/Edit.cshtml
@using GymWebApp.Data.ViewModels
@model TrainingVM
@using GymWebApp.Data.Enums
@{
    ViewData["Title"] = "Edit training";
}

<h2 class="text-center">Modifică un antrenament </h2>
<br />
<div class="row">
    <div class="col-md-8 offset-2">
        <form method="post" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Picture" class="control-label"></label>
                        <input asp-for="Picture" class="form-control" />
                        <span asp-validation-for="Picture" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="StartHour" class="control-label"></label>
                        <input asp-for="StartHour" type="time" class="form-control" />
                        <span asp-validation-for="StartHour" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FinishHour" class="control-label"></label>
                        <input asp-for="FinishHour" type="time" class="form-control" />
                        <span asp-validation-for="FinishHour" class="text-danger"></span>
                    </div>



                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Category" class="control-label"></label>
                        <select asp-for="Category" class="form-control" asp-items="Html.GetEnumSelectList<TrainingCategory>()"></select>
                        <span asp-validation-for="Category" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="TrainerId" class="control-label"></label>
                        <select asp-for="TrainerId" class="form-control" asp-items="ViewBag.Trainers"></select>
                        <span asp-validation-for="TrainerId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SubscriptionId" class="control-label"></label>
                        <select asp-for="SubscriptionId" class="form-control" asp-items="ViewBag.Subscriptions"></select>
                        <span asp-validation-for="SubscriptionId" class="text-danger"></span>
                    </div>

                </div>

                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <textarea asp-for="Description" class="form-control"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
            </div>


            <div class="form-group">
                <input type="submit" value="Editează" class=" btn btn-info" />
                <a asp-action="Index" class="btn btn-primary float-right"><i class="bi bi-arrow-left-circle"></i>Înapoi la listă</a>
            </div>




        </form>
    </div>
</div>

FitnessWebApp/Views/Trainings/Index.cshtml
@using GymWebApp.Models
@model IEnumerable<Training>

@{
    ViewData["Title"] = "List of fitness trainings";
}

<h1 class="text-center">Lista antrenamentelor disponibile în fiecare zi</h1>
<br />
<div class="row">
    @{
        foreach (var item in Model)
        {
            <div class="col-md-4 col-xs-6 border-primary mb-3">
                @*<div class="row">*@
                @*<div class="col-md-12">*@
                <img src="@item.Picture" alt="@item.Name" style="max-width: 300px" class="rounded">
                <h3>
                    <a asp-controller="Trainings" asp-action="Details" asp-route-id="@item.Id">@item.Name</a>
                </h3>

                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <a class=" btn btn-outline-info" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil "></i>Editează</a>
                }


            </div>
        }


    }
</div>

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div style="position:fixed; right: 25px; bottom:65px;">
        <a asp-action="Create" class="btn btn-success"><i class="bi bi-plus-clipboard2-plus"></i>Adaugă</a>
    </div>
}